/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitsRouteImport } from './routes/visits'
import { Route as SurgeriesRouteImport } from './routes/surgeries'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsIndexRouteImport } from './routes/patients/index'
import { Route as PatientsAddRouteImport } from './routes/patients/add'
import { Route as PatientsIdIndexRouteImport } from './routes/patients/$id/index'
import { Route as PatientsIdVisitsAddRouteImport } from './routes/patients/$id/visits/add'
import { Route as PatientsIdVisitsVisitIdRouteImport } from './routes/patients/$id/visits/$visitId'
import { Route as PatientsIdSurgeriesAddRouteImport } from './routes/patients/$id/surgeries/add'
import { Route as PatientsIdSurgeriesSurgeryIdRouteImport } from './routes/patients/$id/surgeries/$surgeryId'

const VisitsRoute = VisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const SurgeriesRoute = SurgeriesRouteImport.update({
  id: '/surgeries',
  path: '/surgeries',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsAddRoute = PatientsAddRouteImport.update({
  id: '/patients/add',
  path: '/patients/add',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdIndexRoute = PatientsIdIndexRouteImport.update({
  id: '/patients/$id/',
  path: '/patients/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdVisitsAddRoute = PatientsIdVisitsAddRouteImport.update({
  id: '/patients/$id/visits/add',
  path: '/patients/$id/visits/add',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdVisitsVisitIdRoute = PatientsIdVisitsVisitIdRouteImport.update({
  id: '/patients/$id/visits/$visitId',
  path: '/patients/$id/visits/$visitId',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdSurgeriesAddRoute = PatientsIdSurgeriesAddRouteImport.update({
  id: '/patients/$id/surgeries/add',
  path: '/patients/$id/surgeries/add',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdSurgeriesSurgeryIdRoute =
  PatientsIdSurgeriesSurgeryIdRouteImport.update({
    id: '/patients/$id/surgeries/$surgeryId',
    path: '/patients/$id/surgeries/$surgeryId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finance': typeof FinanceRoute
  '/surgeries': typeof SurgeriesRoute
  '/visits': typeof VisitsRoute
  '/patients/add': typeof PatientsAddRoute
  '/patients/': typeof PatientsIndexRoute
  '/patients/$id/': typeof PatientsIdIndexRoute
  '/patients/$id/surgeries/$surgeryId': typeof PatientsIdSurgeriesSurgeryIdRoute
  '/patients/$id/surgeries/add': typeof PatientsIdSurgeriesAddRoute
  '/patients/$id/visits/$visitId': typeof PatientsIdVisitsVisitIdRoute
  '/patients/$id/visits/add': typeof PatientsIdVisitsAddRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/finance': typeof FinanceRoute
  '/surgeries': typeof SurgeriesRoute
  '/visits': typeof VisitsRoute
  '/patients/add': typeof PatientsAddRoute
  '/patients': typeof PatientsIndexRoute
  '/patients/$id': typeof PatientsIdIndexRoute
  '/patients/$id/surgeries/$surgeryId': typeof PatientsIdSurgeriesSurgeryIdRoute
  '/patients/$id/surgeries/add': typeof PatientsIdSurgeriesAddRoute
  '/patients/$id/visits/$visitId': typeof PatientsIdVisitsVisitIdRoute
  '/patients/$id/visits/add': typeof PatientsIdVisitsAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/finance': typeof FinanceRoute
  '/surgeries': typeof SurgeriesRoute
  '/visits': typeof VisitsRoute
  '/patients/add': typeof PatientsAddRoute
  '/patients/': typeof PatientsIndexRoute
  '/patients/$id/': typeof PatientsIdIndexRoute
  '/patients/$id/surgeries/$surgeryId': typeof PatientsIdSurgeriesSurgeryIdRoute
  '/patients/$id/surgeries/add': typeof PatientsIdSurgeriesAddRoute
  '/patients/$id/visits/$visitId': typeof PatientsIdVisitsVisitIdRoute
  '/patients/$id/visits/add': typeof PatientsIdVisitsAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/finance'
    | '/surgeries'
    | '/visits'
    | '/patients/add'
    | '/patients/'
    | '/patients/$id/'
    | '/patients/$id/surgeries/$surgeryId'
    | '/patients/$id/surgeries/add'
    | '/patients/$id/visits/$visitId'
    | '/patients/$id/visits/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/finance'
    | '/surgeries'
    | '/visits'
    | '/patients/add'
    | '/patients'
    | '/patients/$id'
    | '/patients/$id/surgeries/$surgeryId'
    | '/patients/$id/surgeries/add'
    | '/patients/$id/visits/$visitId'
    | '/patients/$id/visits/add'
  id:
    | '__root__'
    | '/'
    | '/finance'
    | '/surgeries'
    | '/visits'
    | '/patients/add'
    | '/patients/'
    | '/patients/$id/'
    | '/patients/$id/surgeries/$surgeryId'
    | '/patients/$id/surgeries/add'
    | '/patients/$id/visits/$visitId'
    | '/patients/$id/visits/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinanceRoute: typeof FinanceRoute
  SurgeriesRoute: typeof SurgeriesRoute
  VisitsRoute: typeof VisitsRoute
  PatientsAddRoute: typeof PatientsAddRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
  PatientsIdIndexRoute: typeof PatientsIdIndexRoute
  PatientsIdSurgeriesSurgeryIdRoute: typeof PatientsIdSurgeriesSurgeryIdRoute
  PatientsIdSurgeriesAddRoute: typeof PatientsIdSurgeriesAddRoute
  PatientsIdVisitsVisitIdRoute: typeof PatientsIdVisitsVisitIdRoute
  PatientsIdVisitsAddRoute: typeof PatientsIdVisitsAddRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visits': {
      id: '/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof VisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surgeries': {
      id: '/surgeries'
      path: '/surgeries'
      fullPath: '/surgeries'
      preLoaderRoute: typeof SurgeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/add': {
      id: '/patients/add'
      path: '/patients/add'
      fullPath: '/patients/add'
      preLoaderRoute: typeof PatientsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id/': {
      id: '/patients/$id/'
      path: '/patients/$id'
      fullPath: '/patients/$id/'
      preLoaderRoute: typeof PatientsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id/visits/add': {
      id: '/patients/$id/visits/add'
      path: '/patients/$id/visits/add'
      fullPath: '/patients/$id/visits/add'
      preLoaderRoute: typeof PatientsIdVisitsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id/visits/$visitId': {
      id: '/patients/$id/visits/$visitId'
      path: '/patients/$id/visits/$visitId'
      fullPath: '/patients/$id/visits/$visitId'
      preLoaderRoute: typeof PatientsIdVisitsVisitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id/surgeries/add': {
      id: '/patients/$id/surgeries/add'
      path: '/patients/$id/surgeries/add'
      fullPath: '/patients/$id/surgeries/add'
      preLoaderRoute: typeof PatientsIdSurgeriesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id/surgeries/$surgeryId': {
      id: '/patients/$id/surgeries/$surgeryId'
      path: '/patients/$id/surgeries/$surgeryId'
      fullPath: '/patients/$id/surgeries/$surgeryId'
      preLoaderRoute: typeof PatientsIdSurgeriesSurgeryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinanceRoute: FinanceRoute,
  SurgeriesRoute: SurgeriesRoute,
  VisitsRoute: VisitsRoute,
  PatientsAddRoute: PatientsAddRoute,
  PatientsIndexRoute: PatientsIndexRoute,
  PatientsIdIndexRoute: PatientsIdIndexRoute,
  PatientsIdSurgeriesSurgeryIdRoute: PatientsIdSurgeriesSurgeryIdRoute,
  PatientsIdSurgeriesAddRoute: PatientsIdSurgeriesAddRoute,
  PatientsIdVisitsVisitIdRoute: PatientsIdVisitsVisitIdRoute,
  PatientsIdVisitsAddRoute: PatientsIdVisitsAddRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
